# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The track created behind me - my journey of a developer
email: klimek.mariusz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "One of the main reasons I blog is because I have a really, really bad memory." – Matt Mullenweg
baseurl: "/devblog" # the subpath of your site, e.g. /blog
url: "https://mariuszklimek.github.io/devblog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MauriceKlimek
github_username:  klimcio

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: maurice-devblog

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
